Avoid calling original error handler with NULL reference
systopia/de.systopia.moregreetings pull request #36
Opened 2023-03-05 11:57 UTC by vbrosch

Hi,

first of all, thanks for your helpful extension. We needed to make two small adjustments to get it running smoothly with PHP 8.1. I see that you already made `$errContext` an optional parameter after the last release.

Apart from that, in our development environment (based on the official wordpress docker image and caddy) `set_error_handler` returns `NULL` which is the reason why calling `call_user_func` throws an exception.

I just wanted to provide our small fix for this issue. I don't know if it has any value for you...

We are using PHP 8.1, WordPress 6.1.1 and CiviCRM 5.59 btw.

Greetings
Valentin

2023-03-06 13:43 UTC, jensschuppe requested changes
This makes very much sense as `set_error_handler()` returns `NULL` when the internal error handler is used, which doesn't seem to have been the case in our tests. Although, let's check for the stored handler being a callable as that's the only thing `call_user_func()` accepts.

Also, I think in the case of the internal error handler being used, we'd need to explicitly call `trigger_error()` for it to be invoked here. I'm not sure, however, if that's still necessary now that *Smarty* errors should always throw exceptions instead of resulting in fatals with civicrm/civicrm-core#25334 - would you be able to verify that. @vbrosch?

2023-03-06 13:43 UTC, jensschuppe commented on CRM/Moregreetings/Form/Settings.php
> +    if (!empty(static::$_original_error_handler)) {
```suggestion
    if (is_callable(static::$_original_error_handler)) {
```

2023-03-07 10:52 UTC, vbrosch commented
@jensschuppe Thanks for your suggested fix, I agree that `is_callable` is more appropriate :-) 

In our installation `packages/Smarty/Smarty.class.php` still contains `trigger_error` (line 1100), so I think that using the error handler is still required? I tried to remove it, but there is no exception thrown that could be catched.

2023-03-20 09:32 UTC, jensschuppe commented
Thinking more about it, I think we should have a Core version guard for whether we set our own error handler or not, as with https://github.com/civicrm/civicrm-core/pull/25334 there should be no need for intercepting anymore and our error handler might not get reset. This needs more testing ...

2023-10-07 18:24 UTC, closed without merging

2023-10-09 07:46 UTC, jensschuppe commented
I included the change proposed here in #40, see 645383e0aeddcb95bb811f6be8b4999e83422da2.